id: A432AA6A9
title: A Prayer to Parṇaśavarī
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:07:32.763120
  last_modified_at: 2022-02-28 23:07:32.763122
