id: A432AA6A9
title: Visualization and Mantra Recitation of the Great Compassionate One
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:07:32.776858
  last_modified_at: 2022-02-28 23:07:32.776860
