id: A432AA6A9
title: The Outer, Inner and Secret Refuge Prayer
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:07:32.772762
  last_modified_at: 2022-02-28 23:07:32.772766
