id: A432AA6A9
title: A Prayer
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:07:32.764252
  last_modified_at: 2022-02-28 23:07:32.764255
