id: A432AA6A9
title: Golden Drink (Serkyem) and Torma Offering
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:07:32.769303
  last_modified_at: 2022-02-28 23:07:32.769307
