id: A432AA6A9
title: The Verse for Offering Water from the Pure Vision, An Ocean of Accomplishments
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - nl
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:07:32.775441
  last_modified_at: 2022-02-28 23:07:32.775446
