id: A432AA6A9
title: A Prayer to Padmasambhava
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:07:32.761815
  last_modified_at: 2022-02-28 23:07:32.761818
